
# Pull the Mirsoft sdk image
FROM mcr.microsoft.com/dotnet/sdk:5.0

# This is used for Captcha
# install System.Drawing native dependencies
# RUN apt-get update \
#    && apt-get install -y --allow-unauthenticated \
#        libc6-dev \
#        libgdiplus \
#        libx11-dev \
#     && rm -rf /var/lib/apt/lists/*

# Store files in the app folder (so cliche)
WORKDIR /app
COPY ./Source  ./

WORKDIR /app/Api

# Restore all dotnet nuget packages
RUN dotnet restore

# install dotnet-ef tool 
RUN dotnet tool install --global dotnet-ef

# add it to the env
RUN export PATH="$PATH:/root/.dotnet/tools"

# expose port
EXPOSE 5000

# RUN chmod 777 -R .
WORKDIR /app/Api

# Set default command to RUN
CMD ["dotnet", "watch", "run"]


